google/cloud/spanner_v1/pool.py, google/cloud/spanner_v1/session.py, google/cloud/spanner_v1/transaction.py, tests/unit/test_pool.py, tests/unit/test_session.py, tests/unit/test_transaction.py
=> feat(spanner): exporting transaction._rolled_back as transaction.rolled_back

google/cloud/spanner_v1/client.py, google/cloud/spanner_v1/database.py, google/cloud/spanner_v1/instance.py, noxfile.py, tests/system/test_system.py, tests/unit/test_client.py, tests/unit/test_database.py
Add support for emulators.
To use an emulator, set the environment flag to the gRPC server host:
e.g. $ export SPANNER_EMULATOR_HOST=localhost:9010
Avoid using http schemes in the emulator host as it can cause the gRPC DNS resolver to endlessly attempt to resolve.
Closes #7
=> feat(spanner): add emulator support

google/cloud/spanner_v1/pool.py
Currently the timeout that is used for getting a session from the pool is mistakenly being used for the batch_create_sessions calls that are used to initially fill pools. If the timeout is short, the call does not have time to complete and the pools fails to initialize. Removing this timeout means [the default timeout for BatchCreateSessions](https://github.com/googleapis/python-spanner/blob/master/google/cloud/spanner_v1/gapic/spanner_client_config.py#L44) will be used.
=> fix: remove erroneous timeouts for batch_create_session calls

tests/system/test_system.py
The system tests import pytest to skip a single test. This functionality is supported by unittest which is already being imported. This PR replaces the usage of pytest in the system tests with unittest.
=> refactor: remove unnecessary import

README.rst, noxfile.py, setup.py
Python 2.7 has been deprecated which means we no longer need to run these tests to ensure compatibility. Removing these will significantly speed up the presubmit checks.
=> chore!: remove Python 2.7 from testing

google/cloud/spanner_v1/_helpers.py, google/cloud/spanner_v1/client.py, google/cloud/spanner_v1/database.py, google/cloud/spanner_v1/session.py, google/cloud/spanner_v1/snapshot.py, google/cloud/spanner_v1/transaction.py, tests/unit/test__helpers.py, tests/unit/test_client.py, tests/unit/test_database.py, tests/unit/test_session.py, tests/unit/test_snapshot.py, tests/unit/test_transaction.py
Adds support for QueryOptions.
The QueryOptions are set in one of three ways (in ascending order of precedence):
* As an argument to the Client constructor.
* Setting the SPANNER_OPTIMIZER_VERSION env variable.
* On a per-query basis.
If the backend implements query hints, for example, to instruct the backend which query optimizer version to use, these query hints will also automatically be supported.
=> feat: implement query options versioning support

noxfile.py
Towards #50
The nox docs session is failing due to the new Sphnix release. This PR pins the install to the previous release until the problem can be debugged.
=>  fix: Pin Sphnix version to last working release

google/cloud/spanner_v1/gapic/transports/spanner_grpc_transport.py
This patch adds keepalives to the GRPC channel every 2 minutes. By default, there are no keepalives to the GRPC channel. There have been issues observed with seeing DEADLINE_EXCEEDED errors at 10 minutes despite the timeout being longer eg 1 hour. Adding keepalives will hopefully address this. [This fix has been added to the Java client for similar reasons](https://github.com/googleapis/java-spanner/pull/11).
=> fix: add keepalive to gRPC channel

google/cloud/spanner_v1/gapic/transports/spanner_grpc_transport.py, synth.py
Currently the gRPC config options in spanner.grpc.config are not being used at all. There are changes being made by the synth file but they are generating an unused variable. This PR makes use of this variable to pass the config options through to the gRPC channel creation.
Fixes #6
=> fix: pass gRPC config options to gRPC channel creation

tests/unit/test_backup.py, tests/unit/test_client.py, tests/unit/test_database.py, tests/unit/test_instance.py
Using the self.assertIsInstance(..., ...) method will give more detailed error information than self.assertTrue(isinstance(..., ...))
=> test: use assertIsInstance where possible

docs/database-usage.rst
The `ddl_statements` fields expects a `list` of `strings`, not a `string`. This aims to make that more clear in the documentation.
If it is required that I open a bug for doc changes let me know and I will be happy to do so!
=> docs: make it clear ddl_statements is a list in docs

CHANGELOG.md, docs/conf.py, noxfile.py
Reopens #50
Unfortunately, synthtool has pinned to sphinx<3.0.0 which means any code regen via synth will cause docs to fail. Until it is updated to support it, we also need to pin to sphinx<3.0.0.
=> docs: re-pin sphinx version

google/cloud/spanner_v1/client.py, google/cloud/spanner_v1/database.py, tests/system/test_system.py, tests/unit/test_database.py
The `endpoint_uris` field has been deprecated which means this support is no longer needed.
=> refactor: remove deprecated resource based routing support

google/cloud/spanner_v1/database.py, tests/unit/test_database.py
Partitioned DML transactions can be aborted by Cloud Spanner. These transactions were not automatically retried by the client library. This PR adds support for automatically retrying aborted partitioned DML statements.
=> feat: add support for retrying aborted partitioned DML statements

google/cloud/spanner_v1/pool.py, google/cloud/spanner_v1/session.py, tests/unit/test_pool.py, tests/unit/test_session.py
Currently, PingingPool pings sessions in the background by calling `session.exists()` which calls `GetSession`. 
Using `SELECT 1` is preferred and is used in other client libraries such as [Go](https://github.com/googleapis/google-cloud-go/blob/53898305c6f21b3c3eef34fcff6c61a2cb36f602/spanner/session.go#L227):
=> refactor: PingingPool pings sessions using SELECT 1

tests/system/test_system.py
The functionality in test_partition_query is supported by the emulator. We should not be skipping it.
=> test: remove unneeded system test skip when using emulator

tests/system/test_system.py
While running the ITs against the Cloud Spanner emulator there were failures relating to result ordering. Spanner doesn't guarantee an order for its results unless specified by the ORDER BY clause. The emulator deliberately shuffles the results so users do not rely on the ordering without ORDER BY. 
This PR updates a test to use ORDER BY to fix an emulator failure. However, since ORDER BY is not supported by partitioned queries, a set of the results is created for comparison in that test instead.
=> test: fix result ordering errors for emulator

google/cloud/spanner_v1/client.py, google/cloud/spanner_v1/database.py, tests/unit/test_client.py
Currently, we do not support setting the emulator host outside of the env flag `SPANNER_EMULATOR_HOST`. 
This PR allows users to set the emulator host by using the `api_endpoint` in `client_options` with `google.auth.credentials.AnonymousCredentials`
e.g.
```
from google.auth.credentials import AnonymousCredentials
from google.cloud import spanner
cred = AnonymousCredentials()
client_options = {'api_endpoint': '0.0.0.0:9010'}
client = spanner.Client(
credentials=cred,
client_options=client_options,
project='emulator-project'
)
```
=> feat: add support for using the emulator programatically

docs/batch-usage.rst
The documentation incorrectly stated that `database.batch()` would return a `Batch` object. The recommended way to get a `Batch` object is to use the `BatchCheckout` as a context manager in a `with` statement. The documentation has been update to reflect this.
Documentation links and minor grammar fixes are also included.
=> docs: update batch-usage reflect the correct usage

docs/database-usage.rst
The PR fixes the following:
- links to other documentation
- confusing wording
- incorrect references to instance instead of database
- incorrect grammar
=> docs: update documentation for database-usage

docs/snapshot-usage.rst
This PR fixes the links to other documentation, updates wording and fixes typos and grammar for `docs/snapshot-usage.rst`.
=> docs: update documentation for snapshot usage

tests/system/test_system.py
This PR allows system tests to be run against the emulator without setting `GOOGLE_APPLICATION_CREDENTIALS` with no warnings.
It also skips `test_transaction_read_w_abort` which fails due to running concurrent transactions which the emulator does not support, and removes skips for `test_execute_partitioned_dml` and `test_partition_read_w_index` which are now supported.
=> test: update system tests for emulator

.kokoro/build.sh
=> ci: set up kokoro system tests to run on separate instances

docs/index.rst, docs/opentelemetry-tracing.rst, google/cloud/spanner_v1/_opentelemetry_tracing.py, google/cloud/spanner_v1/batch.py, google/cloud/spanner_v1/session.py, google/cloud/spanner_v1/snapshot.py, google/cloud/spanner_v1/transaction.py, noxfile.py, tests/_helpers.py, tests/system/test_system.py, tests/unit/test__opentelemetry_tracing.py, tests/unit/test_batch.py, tests/unit/test_session.py, tests/unit/test_snapshot.py, tests/unit/test_transaction.py
1. Creates spans around batch/snapshot/transaction calls with relevant information that could help debug latency issues + provide insight into spanner calls
2. Removed python2.7 from unit/system tests (since OpenTelemetry does not support 2.7). However since OT is an optional dependency with some extra effort the tests could keep using 2.7, is this desired?
Pool/gRPC metrics are also on my TODO list, they will come in a seperate PR once some issues with the OpenTelemetry Metrics SDK are worked out :)
=> feat: add OpenTelemetry tracing to spanner calls

tests/unit/test_client.py
=> test: fix failing unit test on master

docs/opentelemetry-tracing.rst
The example uses the Cloud Trace exporter, but there is no `pip install` mentioned for it in the example.
\+ misc doc fixes
=> docs: add install reference for cloud trace exporter (opentelemetry)

google/cloud/spanner_v1/client.py, setup.py, tests/unit/test_client.py
=> feat(spanner): add client_options to base class

noxfile.py, setup.py
The unit tests on master are failing due to the 0.13b0 release of opentelemetry. This PR pins the dependency to the latest working version.
=> build: pin opentelemetry dependencies

noxfile.py
In #133, the tracing dependencies were move to extra requirements in the `setup.py`. These are not installed by default. This updates noxfile.py so that the `tracing` requirements are installed when running tests.
=> build: ensure tracing dependencies are installed for tests

docs/client-usage.rst
Adds instructions for how to use a Cloud Spanner emulator with the client.
=> docs: add instructions for using a Cloud Spanner emulator

google/cloud/spanner_v1/snapshot.py, tests/unit/test_snapshot.py
Fixes #120
This fixes the same issue as googleapis/java-spanner#360.
A similar issue was encountered by `bigquery-storage` and was fixed in googleapis/google-cloud-python#9994.
=> fix: resume iterator on EOS internal error

.gitignore, test_utils/scripts/update_docs.sh
Remove a few stray lines that mentioned bigquery, likely copied from https://github.com/googleapis/python-bigquery.
@mf2199 noticed these while working on https://github.com/googleapis/python-spanner-django, where we're using a similar setup.
=> fix: Remove stray bigquery lines in .gitignore, build script

google/cloud/spanner_v1/client.py, tests/unit/test_client.py
=> fix: update list_instances() to use the filter_ arg

samples/samples/backup_sample_test.py
There's a production issue that causes `list_backup_operations` to fail when filtering with metadata. Skipping this test until it is fixed. Unskipping this test will be tracked by #149
=> test: skip failing list_backup_operations sample test

google/cloud/spanner_v1/streamed.py, tests/unit/test_streamed.py
This PR fixes a bug in the `StreamedResultSet` logic for merging chunked values where the chunked value is an array of structs and the chunk boundary splits a struct element in two and the halves aren't correctly merged.
This bug results in the struct element incorrectly being split into two partial struct elements.
**Expected:**
```
('foo', 0.5, DatetimeWithNanoseconds(2020, 1, 1, 0, 0, tzinfo=<UTC>))
```
**Actual:**
```
('foo', 0.5)
('2020-01-01T00:00:00Z',)
```
This bug is caused by an unhandled `Unmergable` error in `_merge_struct`. This PR adds the same handling used for `_merge_array` and a unit test to prove the fix works.
=> fix: handle Unmergable errors when merging struct responses

google/cloud/spanner_dbapi/parse_utils.py, tests/unit/spanner_dbapi/test_cursor.py, tests/unit/spanner_dbapi/test_parse_utils.py
Continuation of the [PR in django-spanner](https://github.com/googleapis/python-spanner-django/pull/516), only DB API part.
=> feat: remove adding a dummy WHERE clause into UPDATE and DELETE statements

google/cloud/spanner_v1/instance.py, samples/samples/backup_sample_test.py
=> test: unskip list_backup_operations sample test

noxfile.py, setup.py
#160 added `sqlparse` as a test dependency only, but included [non-test code that imports it](https://github.com/googleapis/python-spanner/blob/3db4e5f8d729fb35d416691489d13c2fd306361a/google/cloud/spanner_dbapi/parse_utils.py#L22). Running the tests outside of nox gives this error: `E   ModuleNotFoundError: No module named 'sqlparse'`.
This PR makes `sqlparse` a regular non-test dependency.
The version number comes from https://github.com/googleapis/python-spanner-django/commit/2b096c50949db674e2c017cb4e05e9f71bc0e405.
=> fix: Add sqlparse dependency

google/cloud/spanner_v1/instance.py, samples/samples/backup_sample_test.py
Reverts googleapis/python-spanner#170
The PR contains a fix which is a breaking change and should not be part of the PR.
=> Revert "test: unskip list_backup_operations sample test"

tests/system/test_system.py, tests/system/test_system_dbapi.py
Currently, there is no guarantee that the resources created during the system tests are cleaned up as the jobs running the tests can be cancelled before finishing. This means that over time the testing project runs out of resources due to undeleted instances which causes all system tests runs to fail.
This PR adds labels to the instance created for the test so that any instance created for a test that is older than an hour can be identified and deleted. This will keep the testing project from running out of resources over time.
=> test: improve cleanup to prevent RESOURCE_EXHAUSTED error

tests/system/test_system.py, tests/system/test_system_dbapi.py
This PR converts some Spanner API resource protos following https://github.com/googleapis/python-spanner/blob/master/UPGRADING.md#handwritten-surface-changes, and fixes an apparent bug in the system test.
Fixes #198 🦕
=> fix: Convert PBs in system test cleanup

samples/samples/backup_sample.py
Finishing work for Step 3 of https://github.com/googleapis/python-spanner/pull/194. New tag is live in docs.
=> docs: homogenize region tags pt 2

samples/samples/autocommit_test.py
Fixes #211 
The autocommit sample for `dbapi` fails when the transaction is aborted as the implementation cannot contain retry logic. This means the test must retry on `Aborted` errors instead.
=> test(dbapi): add retry to autocommit sample to reduce flakiness

tests/system/test_system.py, tests/system/test_system_dbapi.py
b/173067462
It seems 30 seconds are too short for mtls test (which uses the system test, and runs on an internal platform). This makes the mtls test very flaky. This PR introduces a `SPANNER_OPERATION_TIMEOUT_IN_SECONDS` env var to make the timeout configurable. 
The default value is now 60 seconds.
=> test: make system test timeout configurable and default to 60 seconds

tests/unit/test_client.py
The assertions for credential scope in the `client` unit tests were broken by [a PR in the auth library](https://github.com/googleapis/google-auth-library-python/pull/665). This does raise the question of whether we should be asserting the scopes like this in this library.
This PR fixes the assertions. Removal of these assertions can be done in a separate PR if it is decided they don't belong in this library.
=> test: fix credential scope assertions

google/cloud/spanner_dbapi/cursor.py, tests/unit/spanner_dbapi/test_cursor.py
Fixes #225 
This PR include error related unit tests to raise the coverage of "DB_API".
=> fix(db_api): use correct connection attribute when handling Aborted errors

google/cloud/spanner_dbapi/cursor.py
According to [PEP 249](https://www.python.org/dev/peps/pep-0249/#lastrowid), `lastrowid` should be set to `None` if it's impossible to set it correctly.
=> fix(db_api): add dummy lastrowid attribute

google/cloud/spanner_v1/_helpers.py, tests/unit/test__helpers.py
=> fix: use datetime timezone info when generating timestamp strings

google/cloud/spanner_dbapi/parse_utils.py, tests/unit/spanner_dbapi/test_connection.py, tests/unit/spanner_dbapi/test_parse_utils.py
=> fix(db_api): update parse_util output for homogeneous statements

google/cloud/spanner_v1/backup.py, google/cloud/spanner_v1/database.py, google/cloud/spanner_v1/instance.py, tests/system/test_system.py, tests/unit/test_backup.py, tests/unit/test_database.py
Implements support for PITR.
With this functionality users will be able to:
- set the retention period for their databases.
- set version time of the database when creating a backup
Creating a backup with a specific version time is shown below:
```
backup = instance.backup(backup_id, expire_time=expire_time, version_time=version_time)
backup.create()
```
=> feat: add support for Point In Time Recovery (PITR)

test.py, tests/system/test_system.py
This PR fixes the assertion to use `metadata.backup_info.version_time` instead of `metadata.backup_info.create_time`. It looks it was passing before the backend correctly supported it and I forgot to re-run the tests before merging #148 (whoops!) and so it is currently failing and preventing #205 from being merged:
https://source.cloud.google.com/results/invocations/8f0f5dab-1b35-4ce3-bb72-0ce9e79ab89d/targets/cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-spanner%2Fpresubmit%2Fpresubmit/log
=> test: fix PITR restored database version time assertion

google/cloud/spanner_v1/batch.py, google/cloud/spanner_v1/database.py, google/cloud/spanner_v1/instance.py, google/cloud/spanner_v1/session.py, google/cloud/spanner_v1/transaction.py, tests/unit/test_batch.py, tests/unit/test_database.py, tests/unit/test_instance.py, tests/unit/test_session.py, tests/unit/test_transaction.py
This PR adds support for logging commit statistics when requested by the user via `log_commit_stats`.
Commit statistics will be logged at the INFO log level.
The default logger will log commit stats using `sys.stderr`, however the user can pass their own logger when constructing the database if needed.
A sample of how to use the feature is given below:
```
database = instance.database(database_id, logger=custom_logger)
database.log_commit_stats = True
```
Once `log_commit_stats` is set, commit stats will be logged via the database logger any time commit is called by the library.
=> feat: add support to log commit stats

google/cloud/spanner_v1/_helpers.py, google/cloud/spanner_v1/streamed.py, tests/unit/test__helpers.py, tests/unit/test_snapshot.py, tests/unit/test_streamed.py
This PR fixes performance issues that were introduced during the mirgration to v2 and optimizes several streaming methods. 
From v2 onwards, the library uses `proto-plus` to produce user friendly Python object to represent proto messages. Unfortunately, it significantly impacted the performance of streaming for cases with many columns as the library must unnecessarily parse the types many times. By reverting the streaming changes to use the raw protobuf messages, the streaming speed is greatly improved.
Fixes #207, fixes #234
=> perf: improve streaming performance

docs/api-reference.rst, docs/index.rst, docs/table-api.rst, docs/table-usage.rst, google/cloud/spanner_v1/database.py, google/cloud/spanner_v1/instance.py, google/cloud/spanner_v1/table.py, tests/system/test_system.py, tests/unit/test_database.py, tests/unit/test_table.py
Adds Table-management methods required by PSO data validation tool.
Fixes #156 🦕
=> feat: add `Database.list_tables` method

google/cloud/spanner_v1/streamed.py
This PR removes a print statement that was mistakenly merged as part of #240. Whoops!
=> fix: remove print statement

samples/samples/backup_sample.py
Instead of using the earliest version time of the database, uses the current time (from spanner). If we used the earliest version time of the database instead we would be creating an empty backup, since the database we are backing up is not 1 hour old (default version retention period).
=> samples: PITR samples backup fix

samples/samples/backup_sample.py, samples/samples/backup_sample_test.py
Instead of hardcoding the version time in the create backup sample, parameterises it.
=> samples: parameterises create backup version time

google/cloud/spanner_dbapi/connection.py, google/cloud/spanner_dbapi/cursor.py
=> refactor(db_api): remove unused variables and add docs

google/cloud/spanner_v1/transaction.py, samples/samples/backup_sample.py, tests/unit/test_transaction.py
feat: Added support for custom timeout and retry parameters in transactions.
Fixes #71 🦕
=> feat: add support for custom timeout and retry parameters in execute_update method in transactions

google/cloud/spanner_v1/_helpers.py, google/cloud/spanner_v1/backup.py, google/cloud/spanner_v1/batch.py, google/cloud/spanner_v1/client.py, google/cloud/spanner_v1/database.py, google/cloud/spanner_v1/instance.py, google/cloud/spanner_v1/keyset.py, google/cloud/spanner_v1/param_types.py, google/cloud/spanner_v1/pool.py, google/cloud/spanner_v1/session.py, google/cloud/spanner_v1/snapshot.py, google/cloud/spanner_v1/streamed.py, google/cloud/spanner_v1/transaction.py
=> docs: fix docstring types and typos

google/cloud/spanner_dbapi/cursor.py, tests/unit/spanner_dbapi/test_cursor.py
With this change users will be able to put several DDLs into one `execute()` call, like:
```python
cursor.execute("CREATE TABLE ...;CREATE INDEX...")
```
=> feat(db_api): support executing several DDLs separated by semicolon

google/cloud/spanner_v1/backup.py, google/cloud/spanner_v1/database.py, google/cloud/spanner_v1/instance.py, tests/system/test_system.py, tests/unit/test_backup.py, tests/unit/test_database.py, tests/unit/test_instance.py
=> feat: add support for CMEK

google/cloud/spanner_v1/backup.py, tests/system/test_system.py, tests/unit/test_backup.py
The `Backup` proto message does not contain an `encryption_config` field. Since all the other properties on the handwritten `Backup` wrapper map to a proto field, there is a risk of confusing users by having `encryption_config` as a property as it will not be updated by the backend when `reload()` is called. To prevent this confusion, this PR removes this property.
=> refactor: remove encryption_config property from Backup

google/cloud/spanner_v1/streamed.py, tests/unit/test_streamed.py
=> fix: avoid consuming pending null values when merging

google/cloud/spanner_v1/database.py, tests/unit/test_database.py
This PR adds the missing support for reading `encryption_info` of a `Database`.
=> feat: add encryption_info to Database

google/cloud/spanner_v1/database.py, google/cloud/spanner_v1/session.py, google/cloud/spanner_v1/snapshot.py, samples/samples/backup_sample.py, tests/unit/test_database.py, tests/unit/test_snapshot.py, tests/unit/test_transaction.py
Added retry and timeout params to partition read in database and snapshot class
Fixes #71 🦕
=> feat: added retry and timeout params to partition read in database and snapshot class

google/cloud/spanner_dbapi/parse_utils.py, tests/unit/spanner_dbapi/test_parse_utils.py
This PR reverts changes made in #233.
I've executed SQLAlchemy tests several times - looks like with #233 changes reverted everything is working fine now. I've mentioned that DLL `test_create` is failing when 223 is reverted, but it's no more actual, so we can safely revert it I assume - I only have those 3 tests mentioned in [the comment](https://github.com/cloudspannerecosystem/python-spanner-sqlalchemy/pull/33#issuecomment-802853769) failing, which is expected for now.
=> fix(db_api): revert Mutations API usage

google/cloud/spanner_dbapi/connection.py, google/cloud/spanner_dbapi/cursor.py, tests/system/test_system_dbapi.py
This PR ensures that DDL statements are being executed. 
Currently, DDL statements aren't executed until a non-DDL statement is executed. This leads to unexpected behavior. This fix will execute DDL statements immediately when `autocommit=True` and when `commit()` is called for `autocommit=False`.
Note that DDL statements will still be executed when a non-DDL statements is executed in `autocommit=False`. e.g.
```
cur.execute(
"""
CREATE TABLE Singers (
SingerId     INT64 NOT NULL,
Name    STRING(1024),
) PRIMARY KEY (SingerId)
"""
)
cur.execute(
"""
INSERT INTO Singers (SingerId, Name) VALUES (1, "Name")
"""
)
```
=> fix(db_api): ensure DDL statements are being executed

docs/snapshot-usage.rst
Fix a wrong keyword argument `key_set`.
Correctly, it is `keyset`, and the value must be a instance of `spanner.KeySet()`.
`snapshot.read()` and `snapshot.execute_sql()` returns an iterable.
It does not have `rows` attribute.
=> docs: fix snapshot usage

google/cloud/spanner_dbapi/parse_utils.py, tests/unit/spanner_dbapi/test_parse_utils.py
Spanner supports doing INSERT with values takes from a SELECT clause. However, DB API is processing such a cases incorrectly, so such a query, for example:
```sql
INSERT INTO manual_pk (id, data)
SELECT manual_pk.id + %s AS anon_1, manual_pk.data
FROM manual_pk
WHERE manual_pk.data IN (%s, %s)
```
Will fail with a syntax error:
```
400 Syntax error: Illegal input character \"%\" [at 3:23]\nSELECT manual_pk.id + %s AS anon_1, manual_pk.data\n
```
Fixing this bug.
=> fix: support INSERT from SELECT clause with args

google/cloud/spanner_v1/database.py, google/cloud/spanner_v1/snapshot.py, tests/unit/test_snapshot.py
=> fix: correctly set resume token when restarting streams

google/cloud/spanner_v1/_helpers.py, google/cloud/spanner_v1/streamed.py, tests/unit/test_streamed.py
To fix performance issues in #207, the streaming logic switched to using the underlying protobuf objects instead of the `proto-plus` objects which have an type conversion overhead when accessing values. However, the metadata proto was kept in the `proto-plus` format. This metadata object contains the type information of the different fields which means it is frequently accessed when iterating over arrays. This causes major performance issues for large scale arrays due to the type conversion overhead. Using the underlying protobuf for the metadata removes this overhead and brings the performance in line with `v1.17.1`.
Fixes #310
=> perf: use protobuf for metadata to reduce type conversions

google/cloud/spanner_dbapi/cursor.py, tests/unit/spanner_dbapi/test_cursor.py
A `PeekIterator` object (used by `Cursor` as a wrapper around the results iterator) does a preliminary stream of the first resulting row (to get the metadata of the response itself). In such a case, if an `Aborted` exception happened, it'll not be retried - fixing this error.
Fixes #342
=> fix: retry Aborted errors when creating PeekIterator

tests/unit/test__helpers.py
refactor: removed test_w_numeric as it was redundant to test_w_numeric_precision_and_scale_valid.
Fixes #339 🦕
=> refactor: remove test_w_numeric due to redundancy 

owlbot.py
There is [an issue](https://github.com/googleapis/python-spanner/blob/master/owlbot.py#L30) in the `owlbot.py` file added in #319 in that [s.remove_staging_dirs()](https://github.com/googleapis/synthtool/blob/master/synthtool/transforms.py#L309) should only be called once after all the files are copied over.  [get_staging_dirs()](https://github.com/googleapis/synthtool/blob/master/synthtool/transforms.py#L280) will only return staging directories that exist.
=> chore: s.remove_staging_dirs() should only be called once

google/cloud/spanner_v1/_helpers.py, google/cloud/spanner_v1/client.py, tests/unit/test__helpers.py, tests/unit/test_client.py
=> feat: add query statistics package support

google/cloud/spanner_dbapi/cursor.py, google/cloud/spanner_dbapi/parse_utils.py, tests/unit/spanner_dbapi/test_cursor.py
Instead of simple `str.split(";")` method use more smart `sqlparse` package to split DDL statements executed in a form:
```python
cursor.execute("""
ddl_statement1;
ddl_statement2;
ddl_statement3;
""")
```
=> fix(db_api): use sqlparse to split DDL statements

samples/samples/snippets.py
=> feat: update query stats samples

google/cloud/spanner_dbapi/cursor.py, test.py, tests/unit/spanner_dbapi/test_cursor.py
Currently an SQL statement such as `"CREATE TABLE t (...); INSERT INTO T (...)"` would be classified as batched DDL despite not all the statements being DDL.
This PR adds a classification check for each of the statements and raises an error if any of the batched statements are non-DDL.
=> fix: classify batched DDL statements

google/cloud/spanner_v1/client.py, google/cloud/spanner_v1/instance.py, tests/system/test_system.py, tests/unit/test_client.py, tests/unit/test_instance.py
Allow users to create an instance using `processing_units`.
1 node = 1000 processing units. There is currently a default node count used if node count is not specified.
`create` and `update` now only update processing units rather than node count, as only one can be specified.
=> feat: add support for low-cost instances

samples/samples/quickstart_test.py, samples/samples/snippets_test.py
Also cleans up old instances and drops the new instance after the test.
Fixes #390 🦕
=> test: create instance before patching quickstart

samples/samples/autocommit_test.py, samples/samples/backup_sample_test.py, samples/samples/quickstart_test.py, samples/samples/snippets.py, samples/samples/snippets_test.py
Make leaked instances more obviously debuggable
=> chore: add sample name label to created instances

samples/samples/autocommit_test.py, samples/samples/backup_sample_test.py, samples/samples/conftest.py, samples/samples/quickstart.py, samples/samples/quickstart_test.py, samples/samples/requirements-test.txt, samples/samples/snippets.py, samples/samples/snippets_test.py
Per discussion with @larkee in PR #418.
=> tests: refactor samples fixtures

tests/unit/spanner_dbapi/test_connect.py, tests/unit/spanner_dbapi/test_connection.py, tests/unit/spanner_dbapi/test_cursor.py
=> tests: avoid using real credentials unit tests

samples/samples/conftest.py
Toward #435, #436, #437.
Note on CI:  we seem to be in a mode currently where the service account used for CI is quota-starved for some operations (instance admin, at least).  All this PR does is remove an early failure in the samples, where different jobs race to do the cleanup of old instances before beginning the actual sample run.
=> tests: harden old instance cleanup against NotFound

google/cloud/spanner_v1/streamed.py, tests/unit/test_streamed.py
=> fix: support merging for NUMERIC values

samples/samples/snippets.py
The original `batch_update()` method [returns two values](https://github.com/googleapis/python-spanner/blob/5629bacf780cf79c3af4cda3de50986c82e18c0d/google/cloud/spanner_v1/transaction.py#L315-L321): batch status and row counts, while the sample accepts only one value from the method call (and checks its length, which is always equal to 2).
=> fix(samples): batch_update() results processing error

testing/constraints-3.9.txt
Consensus from today's meeting is that testing against prereleases needs to happen outside the normal presubmit path.
Reverts only part of PR #479.
=> tests: revert testing against prerelease deps on Python 3.9

google/cloud/spanner_dbapi/version.py, tests/system/test_dbapi.py
Closes https://github.com/googleapis/python-spanner-sqlalchemy/issues/115
=> feat: set a separate user agent for the DB API

google/cloud/spanner_dbapi/cursor.py, tests/unit/spanner_dbapi/test_cursor.py
fix: handle google.api_core.exceptions.OutOfRange exception and throw IntegrityError as expected by dbapi standards
Fixes #570 🦕
=> fix: handle google.api_core.exceptions.OutOfRange exception and throw IntegrityError

tests/system/test_backup_api.py
=> fix: remove database_version_time param from test_instance_list_backups

tests/system/_helpers.py
Fixes #557
Fixes #573
Fixes #574
Fixes #575
Fixes #576
Fixes #577
Fixes #578 
Fixes #579
=> test: delete referencing databases before backups

noxfile.py, setup.py, tests/unit/test_client.py
Allow google-api-core<3.0.0dev on previous release of library. Note that this PR is to a new protected branch **v2**, not **main**.
This will be followed by a release PR and is a step towards removing https://github.com/googleapis/google-cloud-python/issues/10566
=> fix(deps): require google-api-core >= 1.31.5, >= 2.3.2 on v2 release

samples/samples/pg_snippets.py, samples/samples/pg_snippets_test.py, samples/samples/snippets.py, samples/samples/snippets_test.py
Samples are provided for INSERT, DELETE, and UPDATE in both GoogleSQL and PostgreSQL dialects. To provide a more compelling example for the INSERT case, a generated column has been added in the "create_database" example so that the generated value can be returned in the INSERT examples.
=> feat: Add snippets for Spanner DML with returning clause

samples/samples/graph_snippets.py, samples/samples/graph_snippets_test.py
Add a few code snippets to illustrate how to use Spanner Graph functionality in Python. These examples resemble other snippets for how various other Spanner features can be used.
Fixes #1185 🦕
=> feat: Create a few code snippets as examples for using Spanner Graph in Python

samples/samples/backup_sample.py, samples/samples/backup_sample_test.py, samples/samples/backup_schedule_samples.py, samples/samples/backup_schedule_samples_test.py, samples/samples/noxfile.py, samples/samples/pg_snippets.py, samples/samples/snippets.py, samples/samples/snippets_test.py
The snippet shows how Repeatable Read can be configured at client and transaction level.
=> docs: Add snippet for Repeatable Read configuration at client and transaction 
