googleapis/python-spanner

google/cloud/spanner_v1/backup.py, google/cloud/spanner_v1/database.py, google/cloud/spanner_v1/instance.py, tests/unit/test_backup.py, tests/unit/test_database.py, tests/unit/test_instance.py
Adds support for the new Cloud Spanner backups feature.
See backup samples for examples of common use cases.
=> feat: add support for backups

docs/transaction-usage.rst
=> docs: Add documentation for using DML statements in a transaction

synth.py
=> docs: Fix incorrect generated return types

synth.py
Accidentally made changes to a generated file in #49 (whoops!)
This PR makes the synthtool generate the same changes.
=> fix: add keepalive changes to synth.py

google/cloud/spanner_v1/streamed.py
=> refactor: remove unused _count attribute from StreamedResultSet class

samples/samples/backup_sample.py
These samples' region tags slightly differ from identical snippets in different languages. The following is the remedy:
1. Merge this PR to fix GitHub source (keep old tag for now)
2. Fix doc code includes to represent the better region tag
3. Submit a second PR to clean-up redundant region tag wrapping
=> docs: homogenize region tags

samples/samples/backup_sample_test.py
=> test: unskip list_backup_operations sample

samples/samples/autocommit_test.py
=> test: deflake autocommit sample test

setup.py
=> build: loosen the proto-plus dependency

setup.py, tests/system/test_system.py
=> chore: loosen opentelemetry dependencies

noxfile.py
See https://github.com/googleapis/synthtool/pull/1011
=> chore: use gcp-sphinx-docfx-yaml

google/cloud/spanner_dbapi/parse_utils.py, tests/unit/spanner_dbapi/test_parse_utils.py
=> fix(db_api): correctly classify select statements that begin with brackets

google/cloud/spanner_v1/session.py
=> docs: fix docstring for session.py

samples/samples/autocommit_test.py, samples/samples/backup_sample_test.py, samples/samples/snippets.py, samples/samples/snippets_test.py
=> ci: label and clean up instanes used for testing samples

samples/samples/snippets.py, samples/samples/snippets_test.py
Fixes #<issue_number_goes_here> 🦕
=> feat: add sample for low cost instances

samples/samples/snippets_test.py
#421 has been created to track unskipping this test in future.
=> test: skip failing query_options sample

samples/samples/snippets_test.py
=> tests: retry 'create_instance_with_processing_units' on 429

.github/sync-repo-settings.yaml
=> ci: make separate systest job required for merge

tests/system/test_backup_api.py
=> tests: use datetime.now() with timezone to handle DST correctly

.github/sync-repo-settings.yaml, .github/workflows/integration-tests-against-emulator.yaml, .kokoro/build.sh, .kokoro/test-samples-impl.sh, CONTRIBUTING.rst, owlbot.py
Unsure how to update https://github.com/googleapis/python-spanner/blob/master/pylint.config.py#L25-L28, filed #548 to keep track of it.
Fixes #547  🦕
=> chore: migrate to main branch

samples/samples/admin/backup_snippet.py, samples/samples/admin/backup_snippet_test.py, samples/samples/admin/samples.py, samples/samples/admin/samples_test.py
Notes
* Adds samples and tests for auto-generated backup admin APIs.
* The sample code style is mostly consistent with our existing samples.
=> docs: samples and tests for admin backup APIs

samples/samples/backup_sample.py, samples/samples/pg_snippets.py, samples/samples/snippets.py
* Updated admin samples to remove usage of handwritten instance and database classes.
=> docs: use autogenerated methods to get names from admin samples

samples/samples/backup_schedule_samples.py, samples/samples/backup_schedule_samples_test.py
This PR adds code samples for the following APIs:
1. CreateBackupSchedule (both full and incremental backup schedules)
2. ListBackupSchedules
3. GetBackupSchedule
4. UpdateBackupSchedule
5. DeleteBackupSchedule
Fixes #1203
=> chore(samples): Add samples for Cloud Spanner Scheduled Backups

samples/samples/archived/backup_snippet_test.py, samples/samples/conftest.py, samples/samples/snippets.py
Fixes #<issue_number_goes_here> 🦕
=> chore: update sample instance edition to ENTERPRISE_PLUS for testing

samples/samples/snippets.py, samples/samples/snippets_test.py
Fixes #<issue_number_goes_here> 🦕
=> docs: add sample for pre-split feature
